# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Expose the port the app runs on
EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]