services:
  feedfront:
    build:
      context: ./feedfront
      dockerfile: ./Dockerfile-prod
    container_name: feedfront-frontend
    ports:
      - "3000:3000"
    networks:
      - feedfront-network
  feedback:
    build:
      context: ./feedback
      dockerfile: ./Dockerfile-prod
    container_name: feedfront-backend
    ports:
      - "3001:3001"
    environment:
      EFREI_API_URL: http://efrei-api:8000
      EFREI_API_KEY: apikey
      DB_NAME: feedfront
      DB_USER: pgsql_feedfront
      DB_PASS: pgsql_pass
      DB_HOST: internal-database
      DB_PORT: 5432
    volumes:
      - ./feedback.env:/app/.env
    networks:
      - feedfront-network
  efrei-api:
    build:
      context: ./efrei-api
      dockerfile: ./Dockerfile-prod
    container_name: feedfront-efrei-api
    ports:
      - "8000:8000"
    networks:
      - feedfront-network
  internal-database:
    image: postgres:17
    container_name: feedfront-internal-database
    restart: always

    # Set shared memory limit when using docker-compose. This is a good practice according to the official PostgreSQL documentation.
    shm_size: 128mb

    environment:
      POSTGRES_USER: pgsql_feedfront
      POSTGRES_PASSWORD: pgsql_pass
      POSTGRES_DB: feedfront
    ports:
      - "5432:5432"
    volumes:
      # SQL script to initialize the database
      - ./internal-db-init.sql:/docker-entrypoint-initdb.d/internal-db-init.sql
      - internaldb:/var/lib/postgresql/data
    networks:
      - feedfront-network
  school-database:
    image: postgres:17
    container_name: feedfront-school-database
    restart: always

    # Set shared memory limit when using docker-compose. This is a good practice according to the official PostgreSQL documentation.
    shm_size: 128mb

    environment:
      POSTGRES_USER: pgsql_school
      POSTGRES_PASSWORD: pgsql_pass
      POSTGRES_DB: school
    ports:
      - "5433:5432"
    volumes:
      # SQL script to initialize the database
      - ./school-db-init.sql:/docker-entrypoint-initdb.d/school-db-init.sql
      - schooldb:/var/lib/postgresql/data
    networks:
      - feedfront-network

volumes:
  internaldb:
  schooldb:

networks:
  feedfront-network:
    driver: bridge
