name: Build, publish and deploy image to server using GHCR.

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    name: Try to build the project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          docker compose -f docker-compose-prod.yml build
  deploy:
    needs: build_and_publish
    name: Deploy image to server
    runs-on: self-hosted
    steps:
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/feedfront && docker compose -f docker-compose-prod.yml down -v && git pull && docker compose -f docker-compose-prod.yml up --build -d && exit"
      - name: cleanup
        run: |
          rm ~/.ssh/id_rsa
          rm ~/.ssh/known_hosts
