name: Merge to Main Pull Request Tests

on:
  pull_request:
    branches: ["main"]

jobs:
  run_tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./feedfront

      - name: Run tests
        run: npm run test
        env:
          NEXT_PUBLIC_BACK_ADDRESS: localhost:3001
        working-directory: ./feedfront
